/*****************************DENUNCIA*************************************/
CREATE TABLE CIDADAO(
IdCidadao INT NOT NULL,
Email VARCHAR(35) NOT NULL,
Celular CHAR(11) NOT NULL,
Nome VARCHAR(30) NOT NULL,
Sobrenome VARCHAR(30) NOT NULL,
Cep CHAR(9) NOT NULL,
CPF CHAR(11) NOT NULL,
TituloEleitor CHAR(12) NOT NULL,
ZonaEleitor CHAR(3) NOT NULL,
Secao CHAR(4) NOT NULL,
ptCidadao INT NOT NULL
);
GO
ALTER TABLE CIDADAO ADD CONSTRAINT CIDADAO_PK PRIMARY KEY (IdCidadao);
ALTER TABLE CIDADAO ADD CONSTRAINT CIDADAO_DF01 DEFAULT 10 FOR ptCidadao;
GO
CREATE TABLE FOTO_CIDADAO(
IdCidadao INT NOT NULL,
VbFotoCidadao IMAGE NOT NULL
);
ALTER TABLE FOTO_CIDADAO ADD CONSTRAINT FOTO_CIDADAO_PK PRIMARY KEY (IdCidadao)
GO
ALTER TABLE FOTO_CIDADAO ADD CONSTRAINT FOTO_CIDADAO_FK FOREIGN KEY (IdCidadao) REFERENCES CIDADAO(IdCidadao)
GO
CREATE TABLE TIPOS_DENUNCIA (
IdTipoDenuncia INT NOT NULL,
dsTipoDenuncia VARCHAR(35) NOT NULL,
ptTipoDenuncia INT NOT NULL
);
ALTER TABLE TIPOS_DENUNCIA ADD CONSTRAINT TIPOS_DENUNCIA_PK PRIMARY KEY (IdTipoDenuncia)
GO
ALTER TABLE TIPOS_DENUNCIA ADD CONSTRAINT TIPOS_DENUNCIA_DF01 DEFAULT 15 FOR ptTipoDenuncia
GO
INSERT INTO TIPOS_DENUNCIA (IdTipoDenuncia, dsTipoDenuncia) VALUES (1,'');
INSERT INTO TIPOS_DENUNCIA (IdTipoDenuncia, dsTipoDenuncia) VALUES (2,'');
INSERT INTO TIPOS_DENUNCIA VALUES (3,'',20);
INSERT INTO TIPOS_DENUNCIA VALUES (4,'',20);
INSERT INTO TIPOS_DENUNCIA VALUES (5,'',30);
GO
CREATE TABLE STATUS_DENUNCIA(
IdStatus INT NOT NULL,
DescricaoStatus VARCHAR(25) NOT NULL
);
ALTER TABLE STATUS_DENUNCIA ADD CONSTRAINT STATUS_DENUNCIA_PK PRIMARY KEY (IdStatus)
GO
CREATE TABLE DENUNCIA(
IdDenuncia INT NOT NULL,
IdCidadao INT NOT NULL,
IdTipoDenuncia INT NOT NULL,
IdStatus INT NOT NULL,
DataDenuncia DATE NOT NULL,
DescricaoDenuncia VARCHAR(8000)NOT NULL ,
localDenuncia VARCHAR(2000) NOT NULL,
pontosPrioridade INT NOT NULL
);
GO
ALTER TABLE DENUNCIA ADD CONSTRAINT DENUNCIA_PK PRIMARY KEY (IdDenuncia);
ALTER TABLE DENUNCIA ADD CONSTRAINT DENUNCIA_FK01 FOREIGN KEY (IdTipoDenuncia) REFERENCES TIPOS_DENUNCIA(IdTipoDenuncia);
ALTER TABLE DENUNCIA ADD CONSTRAINT DENUNCIA_FK02 FOREIGN KEY (IdCidadao)      REFERENCES CIDADAO(IdCidadao);
ALTER TABLE DENUNCIA ADD CONSTRAINT DENUNCIA_FK03 FOREIGN KEY (IdStatus)       REFERENCES STATUS_DENUNCIA(IdStatus);
GO
CREATE TABLE IMAGEM_DENUNCIA(
IdDenuncia INT NOT NULL,
IdImagemDenuncia INT NOT NULL,
VbImagemDenuncia IMAGE NOT NULL
);
ALTER TABLE IMAGEM_DENUNCIA ADD CONSTRAINT IMAGEM_DENUNCIA_PK PRIMARY KEY (IdDenuncia, IdImagemDenuncia)
GO
ALTER TABLE IMAGEM_DENUNCIA ADD CONSTRAINT  IMAGEM_DENUNCIA_FK01 FOREIGN KEY (IdDenuncia) REFERENCES DENUNCIA(IdDenuncia)
GO
CREATE TABLE APONTAMENTOS(
IdDenuncia INT NOT NULL,
IdApontamento INT NOT NULL,
mtApontamentos SMALLDATETIME NOT NULL,
dsApontamentos VARCHAR(255) NOT NULL
);
ALTER TABLE APONTAMENTOS ADD CONSTRAINT APONTAMENTOS_PK PRIMARY KEY (IdDenuncia, IdApontamento)
GO
ALTER TABLE APONTAMENTOS ADD CONSTRAINT APONTAMENTOS_DF01 DEFAULT CURRENT_TIMESTAMP FOR mtApontamentos;
GO
ALTER TABLE APONTAMENTOS ADD CONSTRAINT APONTAMENTOS_FK01 FOREIGN KEY (IdDenuncia) REFERENCES  DENUNCIA(IdDenuncia)
GO

/***************************************PUBLICAÇÕES****************************************************/
CREATE TABLE TIPOS_PUBLICACOES (
IdTipoPublicacao INT NOT NULL,
dsTipoDenuncia VARCHAR(25) NOT NULL
);
ALTER TABLE TIPOS_PUBLICACOES ADD CONSTRAINT TIPOS_PUBLICACOES_PK PRIMARY KEY (IdTipoPublicacao);
GO
CREATE TABLE PUBLICACOES (
IdPublicacao INT NOT NULL,
IdTipoPublicacao INT NOT NULL,
ttPublicacao VARCHAR(50) NOT NULL,
txPublicacao VARCHAR(8000) NOT NULL,
inPublicacao VARCHAR(250) NOT NULL,
dtInicioExibicao DATETIME NOT NULL,
dtFimExibicao DATETIME NOT NULL,
snPublicacao INTEGER NOT NULL,
prPublicacao INTEGER NOT NULL
);
ALTER TABLE PUBLICACOES ADD CONSTRAINT PUBLICACOES_PK PRIMARY KEY (IdPublicacao)
GO
ALTER TABLE PUBLICACOES ADD CONSTRAINT PUBLICACOES_FK01 FOREIGN KEY (IdTipoPublicacao) REFERENCES TIPOS_PUBLICACOES(IdTipoPublicacao);
GO
CREATE TABLE PUBLICACOES_IMAGENS (
IdPublicacao INT NOT NULL,
IdPublicacaoImagem INT NOT NULL,
vbPublicacaoImagem IMAGE NOT NULL
);
ALTER TABLE PUBLICACOES_IMAGENS ADD CONSTRAINT PUBLICACOES_IMAGENS_PK PRIMARY KEY (IdPublicacaoImagem)
GO
ALTER TABLE PUBLICACOES_IMAGENS ADD CONSTRAINT PUBLICACOES_IMAGENS_FK01 FOREIGN KEY (IdPublicacao) REFERENCES  PUBLICACOES(IdPublicacao)
GO